# Generated by Django 5.0.2 on 2024-02-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='progress_bar',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
