# Generated by Django 5.0.2 on 2024-02-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me_app', '0002_info_progress_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='skills',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
