# Generated by Django 5.0.2 on 2024-02-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me_app', '0004_remove_info_progress_bar_remove_info_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('progress_bar', models.CharField(max_length=100)),
            ],
        ),
    ]
