# Generated by Django 5.0.2 on 2024-02-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me_app', '0005_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='experience',
            field=models.TextField(blank=True),
        ),
    ]
