# Generated by Django 5.0.2 on 2024-02-28 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me_app', '0007_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='full_name',
            new_name='name',
        ),
    ]
